/**
 * n8n.types.ts
 *
 * Shared types for N8nService:
 *  - N8n REST API DTOs (N8nWorkflowDto, N8nApiListResponse)
 *  - Prisma duck-typed client interface (N8nPrismaClient)
 *  - Sync result (SyncResult)
 *  - BridgedSkillSpec — mirrors the interface defined in
 *    packages/mcp-server/src/skill-bridge.ts.
 *    Defined locally to avoid a hard cross-package compile-time dependency;
 *    TypeScript's structural typing guarantees full compatibility with the
 *    real BridgedSkillSpec when skillsToMcpTools() is called at runtime.
 */

// ── Sync result ──────────────────────────────────────────────────────────

export interface SyncResult {
  connectionId: string;
  /** Workflows upserted successfully */
  upserted: number;
  /** Workflows inactive in n8n — skipped, not deleted from DB */
  skipped:  number;
  errors:   Array<{ workflowId: string; reason: string }>;
}

// ── n8n REST API DTOs ────────────────────────────────────────────────────

export interface N8nWorkflowDto {
  id:     string;
  name:   string;
  active: boolean;
  nodes?: Array<{
    type:        string;
    parameters?: {
      path?:       string;
      httpMethod?: string;
    };
  }>;
}

export interface N8nApiListResponse {
  data: N8nWorkflowDto[];
}

// ── Prisma row shapes ────────────────────────────────────────────────────

/** Minimal shape of an N8nConnection row returned from Prisma. */
export interface N8nConnectionRecord {
  id:              string;
  baseUrl:         string;
  apiKeyEncrypted: string;
  isActive:        boolean;
}

/** Minimal shape of an N8nWorkflow row returned from Prisma. */
export interface N8nWorkflowRecord {
  id:             string;
  connectionId:   string;
  n8nWorkflowId:  string;
  name:           string;
  description:    string | null;
  /** JSON Schema describing inputs — null when not provided */
  inputSchema:    unknown;
  webhookUrl:     string | null;
  isActive:       boolean;
}

// ── Prisma duck-typed client ─────────────────────────────────────────────

/**
 * Duck-typed interface for the Prisma client methods used by N8nService.
 * The generated PrismaClient satisfies this interface automatically.
 * Tests can mock it with plain objects.
 */
export interface N8nPrismaClient {
  n8nConnection: {
    findUniqueOrThrow(args: {
      where: { id: string };
    }): Promise<N8nConnectionRecord>;

    findMany(args: {
      where:  { isActive: boolean };
      select: { id: true };
    }): Promise<Array<{ id: string }>>;
  };

  n8nWorkflow: {
    upsert(args: {
      where:  { connectionId_n8nWorkflowId: { connectionId: string; n8nWorkflowId: string } };
      create: {
        connectionId:   string;
        n8nWorkflowId:  string;
        name:           string;
        webhookUrl:     string;
        isActive:       boolean;
      };
      update: {
        name:       string;
        webhookUrl: string;
        isActive:   boolean;
        updatedAt:  Date;
      };
    }): Promise<unknown>;

    findMany(args: {
      where: {
        connectionId: string;
        isActive:     boolean;
        webhookUrl:   { not: null };
      };
    }): Promise<N8nWorkflowRecord[]>;
  };

  skill: {
    upsert(args: {
      where:  { name: string };
      create: {
        name:        string;
        description: string;
        type:        string;
        config:      Record<string, unknown>;
        schema:      null;
      };
      update: {
        description: string;
        config:      Record<string, unknown>;
        updatedAt:   Date;
      };
    }): Promise<unknown>;
  };

  /**
   * Execute multiple operations atomically within a transaction.
   * Supports both array form (parallel execution) and callback form (sequential).
   */
  $transaction<T extends Promise<unknown>[]>(operations: [...T]): Promise<{ [K in keyof T]: Awaited<T[K]> }>;
}

// ── BridgedSkillSpec ─────────────────────────────────────────────────────

/**
 * Mirrors BridgedSkillSpec from packages/mcp-server/src/skill-bridge.ts.
 *
 * Defined locally so that n8n-service does not need a hard compile-time
 * dependency on the mcp-server package. TypeScript's structural typing
 * guarantees these types are fully compatible: any value of this type
 * can be passed directly to skillsToMcpTools() from skill-bridge.ts.
 *
 * Tool name generated by skillsToMcpTools():
 *   `skill__{skill.id}__{fn.name}`
 *
 * For n8n workflows the pattern is:
 *   `skill__n8n_{n8nWorkflowId}__invoke`
 */
export interface BridgedSkillSpec {
  id:          string;
  name:        string;
  description: string;
  category:    string;
  functions: Array<{
    name:         string;
    description:  string;
    inputSchema?: Record<string, unknown>;
  }>;
  /** HTTP endpoint — must be webhookUrl for n8n skills */
  endpoint?: string;
}
